---
# tasks file for k8s-admin
#
- name: package
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - git-secrets

- name: install kubectl and helm3
  community.general.snap:
    name: "{{ item }}"
    state: present
    classic: yes
  with_items:
    - kubectl
    - helm

- ansible.builtin.include_tasks: kustomize.yml

- ansible.builtin.include_tasks: sops.yml
